# Generated by Django 4.0.3 on 2022-03-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
                ('category_date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-category_date_added'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_sender_name', models.CharField(max_length=200)),
                ('message_sender_email', models.EmailField(max_length=200)),
                ('message_sender_mobile_number', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('message_date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-message_date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publisher_date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=100)),
                ('article_created_at', models.DateTimeField(auto_now_add=True)),
                ('article_updated_at', models.DateTimeField(auto_now=True)),
                ('article_image_link', models.URLField()),
                ('article_content', models.TextField()),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPI.categorie')),
                ('article_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPI.publisher')),
            ],
            options={
                'ordering': ['-article_created_at'],
            },
        ),
    ]
